apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  root-password: "yourpassword"
  connection-string: "Server=mysql-service;Port=3306;Database=complimentshop;User=root;Password=yourpassword;"
  # NOTE: In production, use a proper secret management solution like:
  # - Google Secret Manager (for GKE)
  # - Kubernetes Secrets with encryption at rest
  # - External Secrets Operator
  # - Sealed Secrets
